<a href="https://colab.research.google.com/github/bradykuo/Numerical-Optimization/blob/main/CG_method.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import gurobipy as gp
import random


In [ ]:
Diag =[]
for i in range(1,11):
    Diag.append(i*2)
Q = np.diag(Diag)
print(Q)

[[ 2  0  0  0  0  0  0  0  0  0]
 [ 0  4  0  0  0  0  0  0  0  0]
 [ 0  0  6  0  0  0  0  0  0  0]
 [ 0  0  0  8  0  0  0  0  0  0]
 [ 0  0  0  0 10  0  0  0  0  0]
 [ 0  0  0  0  0 12  0  0  0  0]
 [ 0  0  0  0  0  0 14  0  0  0]
 [ 0  0  0  0  0  0  0 16  0  0]
 [ 0  0  0  0  0  0  0  0 18  0]
 [ 0  0  0  0  0  0  0  0  0 20]]


In [ ]:
A=[]
b=[]
A.append([1.5,1,1,0.5,0.5,0,0,0,0,0])
b.append([5.5])
A.append([0,0,0,0,0,2,-0.5,-0.5,1,-1])
b.append([2])
A.append([1,0,1,0,1,0,1,0,1,0])
b.append([10])
A.append([0,1,0,1,0,1,0,1,0,1])
b.append([15])
A = np.array(A)
b = np.array(b)
print(A)
print(b)

[[ 1.5  1.   1.   0.5  0.5  0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   2.  -0.5 -0.5  1.  -1. ]
 [ 1.   0.   1.   0.   1.   0.   1.   0.   1.   0. ]
 [ 0.   1.   0.   1.   0.   1.   0.   1.   0.   1. ]]
[[ 5.5]
 [ 2. ]
 [10. ]
 [15. ]]


In [ ]:
n,m = 10,4
QP = gp.Model("RealMan")
x=[]
for i in range(n):
    x.append(QP.addVar(name = 'X'+ str(i)))


In [ ]:
t,obj =[],0
for j in range(n):
    t.append(0)
    for i in range(n):
        t[j] = t[j] + x[i] * float(Q[i,j])
    obj = obj +t[j]*x[j]

obj = obj/2


In [ ]:
QP.setObjective(obj,gp.GRB.MINIMIZE)

In [ ]:
for i in range(m):
    QP.addConstr(sum((A[i,j]*x[j] for j in range(n))) == b[i], "linear" + str(i))

In [ ]:
QP.optimize()

Gurobi Optimizer version 9.5.2 build v9.5.2rc0 (win64)
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads
Optimize a model with 4 rows, 10 columns and 20 nonzeros
Model fingerprint: 0x31e01e63
Model has 10 quadratic objective terms
Coefficient statistics:
  Matrix range     [5e-01, 2e+00]
  Objective range  [0e+00, 0e+00]
  QObjective range [2e+00, 2e+01]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e+00, 2e+01]
Presolve time: 0.00s
Presolved: 4 rows, 10 columns, 20 nonzeros
Presolved model has 10 quadratic objective terms
Ordering time: 0.00s

Barrier statistics:
 AA' NZ     : 4.000e+00
 Factor NZ  : 1.000e+01
 Factor Ops : 3.000e+01 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   3.18390599e+06 -3.18390599e+06  2.75e+03 0.00e+00  1.01e+06     0s
   1   2.29648925e+04 -1.23747240e+05  1.72e+02 0.00e+00  7.40e+04  

In [ ]:
optimalSolution =[]
for v in QP.getVars():
    optimalSolution.append([v.X])
    print('The decision varible is %s %g' % (v.VarName, v.X))

print('Obj: %g' % obj.getValue())
optimalSolution = np.array(optimalSolution)
A.dot(optimalSolution)-b

The decision varible is X0 1.01579e-12
The decision varible is X1 1.49117
The decision varible is X2 0.746195
The decision varible is X3 3.70779
The decision varible is X4 2.81749
The decision varible is X5 3.18105
The decision varible is X6 3.97639
The decision varible is X7 3.57231
The decision varible is X8 2.45993
The decision varible is X9 3.04769
Obj: 521.632


array([[0.0000000e+00],
       [8.8817842e-16],
       [0.0000000e+00],
       [0.0000000e+00]])

In [ ]:
"""
def CGn(Q,q old_xk,numberMaxStep):
    rk,tk,beatak,dk,printOption=[],[],[],[],0
    xk=[]
    xk.append(old_xk[-1])
    k ,n=0,len(Q)
    if printOption!=0:
        print("The iteration number is %d:" % k)
    print()
"""

'\ndef CGn(Q,q old_xk,numberMaxStep):\n    rk,tk,beatak,dk,printOption=[],[],[],[],0\n    xk=[]\n    xk.append(old_xk[-1])\n    k ,n=0,len(Q)\n    if printOption!=0:\n        print("The iteration number is %d:" % k) \n    print()\n'