In [1]:
import numpy as np 
import random

In [2]:
mu_0=10
r=0.6
epsilon=1e-5

In [3]:
# set A, b, c matrix
n, m = 4, 2
A = [[1, 2, 2, 3], [2, 1, 3, 2]]
b = [[8], [8]]
c = [[1], [2], [3], [4]]
A, b, c = np.array(A), np.array(b), np.array(c)

In [4]:
# set initial solution
x0 = np.array([[1], [1], [1], [1]])
y0 = np.array([[1], [1]])
#s = c-transpose(A) dot y
s0 = ([[random.randint(1, 10)] for _ in range(n)])
e = np.ones((n, 1))

In [5]:
def determineStepSize(x,d,r):
    n=len(d)
    stepSize=float("inf")
    for i in range(n):
        if d[i] < 0 and stepSize>-x[i]/d[i]:
            stepSize=-x[i]/d[i]
    stepSize=min([1,r*stepSize])
    return stepSize

In [9]:
mu=[10]
k = 0

while mu[k]>epsilon*mu_0:
#for k in range(100):
    mu[k] = mu_0*(1/10)**k
    x0=np.array(x0)
    y0=np.array(y0)
    s0=np.array(s0)
    solution=np.vstack((x0,y0,s0))

    X=np.diag(x0[:,0])
    S=np.diag(s0[:,0])

    r1=b-A.dot(x0)
    r2=c-A.transpose().dot(y0)-s0
    r3=mu[k]*e-X.dot(S).dot(e)
    residual=np.vstack((r1,r2,r3))

    A1=np.hstack((A,np.zeros((m, m)),np.zeros((m, n))))
    A2=np.hstack((np.zeros((n, n)),A.transpose(),np.identity(n)))
    A3=np.hstack((S,np.zeros((n, m)),X))
    barA=np.vstack((A1,A2,A3))
    
    NewtonDirection=np.linalg.inv(barA).dot(residual)
    delta_x=NewtonDirection[0:n,0].reshape(n,1)
    delta_y=NewtonDirection[n:n+m,0].reshape(m,1)
    delta_s=NewtonDirection[n+m:n+n+m,0].reshape(n,1)
    
    stepSizeX=determineStepSize(x0,delta_x,r)
    stepSizeS=determineStepSize(s0,delta_s,r)
    x0=x0+stepSizeX*delta_x
    y0=y0+stepSizeS*delta_y
    s0=s0+stepSizeS*delta_s
    
    mu.append((1/10)*x0.transpose().dot(s0)/n)
    print("mu is ",mu[k+1])
    print("stepSizeX is ",stepSizeX)
    print("stepSizeS is ",stepSizeS)
    print('k=',k)
    print(x0)
    print(y0)
    print(s0)
    k += 1    

print("optimal value=",c.transpose().dot(x0))

mu is  [[0.54858837]]
stepSizeX is  [0.09607057]
stepSizeS is  1
k= 0
[[1.06614448]
 [1.06614448]
 [0.96031331]
 [0.96031331]]
[[-0.25143177]
 [-1.25143177]]
[[3.75429532]
 [3.75429532]
 [7.25715887]
 [7.25715887]]
mu is  [[0.24385589]]
stepSizeX is  1
stepSizeS is  [0.67614577]
k= 1
[[1.21243965]
 [1.21243965]
 [0.87253621]
 [0.87253621]]
[[ 0.49942729]
 [-0.50057271]]
[[1.50171813]
 [1.50171813]
 [3.50286355]
 [3.50286355]]
mu is  [[0.11685835]]
stepSizeX is  1
stepSizeS is  [0.52924967]
k= 2
[[1.44110952]
 [1.44110952]
 [0.73533429]
 [0.73533429]]
[[ 0.79977092]
 [-0.20022908]]
[[0.60068725]
 [0.60068725]
 [2.00114542]
 [2.00114542]]
mu is  [[0.0559405]]
stepSizeX is  1
stepSizeS is  [0.4665737]
k= 3
[[1.8698719 ]
 [1.8698719 ]
 [0.47807686]
 [0.47807686]]
[[ 0.91990837]
 [-0.08009163]]
[[0.2402749 ]
 [0.2402749 ]
 [1.40045817]
 [1.40045817]]
mu is  [[0.0223762]]
stepSizeX is  [0.9437944]
stepSizeS is  [0.47293477]
k= 4
[[2.34794876]
 [2.34794876]
 [0.19123074]
 [0.19123074]]
[[ 0.9