In [4]:
import numpy as np
import random


def determineStepSize(x,d,r):
    n=len(d)
    stepSize=float("inf")
    for i in range(n):
        if d[i] < 0 and stepSize>-x[i]/d[i]:
            stepSize=-x[i]/d[i]
            
    stepSize=min([1,r*stepSize])
    return stepSize

def IPM(A,b,c,x0):  
    y0 = [[random.randint(1,100)]]
    s0 = [[random.randint(1,100)],[random.randint(1,100)],[random.randint(1,100)]]
    mu=[10]
    r=0.6
    mu_0=10
    epsilon=1e-6
    e=np.ones((3,1))
    k=0

    while mu[k]>epsilon*mu_0:
        #mu[k]=mu_0*(1/10)**k
        x0=np.array(x0)
        y0=np.array(y0)
        s0=np.array(s0)
        solution=np.vstack((x0,y0,s0))

        X=np.diag(x0[:,0])
        S=np.diag(s0[:,0])

        r1=b-A.dot(x0)
        r2=c-A.transpose().dot(y0)-s0
        r3=mu[k]*e-X.dot(S).dot(e)
        residual=np.vstack((r1,r2,r3))

        A1=np.hstack((A,np.zeros((1,1)),np.zeros((1,3))))
        A2=np.hstack((np.zeros((3,3)),A.transpose(),np.identity(3)))
        A3=np.hstack((S,np.zeros((3,1)),X))
        barA=np.vstack((A1,A2,A3))

        NewtonDirection=np.linalg.inv(barA).dot(residual)
        delta_x=NewtonDirection[0:3,0].reshape(3,1)
        delta_y=NewtonDirection[3:4,0].reshape(1,1)
        delta_s=NewtonDirection[4:7,0].reshape(3,1)

        stepSizeX=determineStepSize(x0,delta_x,r)
        stepSizeS=determineStepSize(s0,delta_s,r)
        x0=x0+stepSizeX*delta_x
        y0=y0+stepSizeS*delta_y
        s0=s0+stepSizeS*delta_s
        #mu[k+1]=(1/10)*x0.transpose().dot(s0)/4#complementary condition
        mu.append((1/10)*x0.transpose().dot(s0)/3)
        print("mu is ",mu[k+1])
        #print("stepSizeX is ",stepSizeX)
        #print("stepSizeS is ",stepSizeS)
        print('k=',k)
        print(x0)
        k=k+1
    print("optimal value =", c.transpose().dot(x0))



In [5]:
#x0 =(1/3, 1/3, 1/3)
A=[[1,1,1]]
b=[[1]]
c=[[1],[1],[0]]
A=np.array(A)
b=np.array(b)
c=np.array(c)

x0 = [[1/3],[1/3],[1/3]]

IPM(A,b,c,x0)

mu is  [[1.14515419]]
k= 0
[[0.33236198]
 [0.33125508]
 [0.33638294]]
mu is  [[0.47288278]]
k= 1
[[0.3294466 ]
 [0.32799353]
 [0.34255987]]
mu is  [[0.20227919]]
k= 2
[[0.32226273]
 [0.32003764]
 [0.35769964]]
mu is  [[0.09262224]]
k= 3
[[0.30460528]
 [0.30082083]
 [0.39457389]]
mu is  [[0.04630573]]
k= 4
[[0.26297331]
 [0.2564904 ]
 [0.48053629]]
mu is  [[0.02328999]]
k= 5
[[0.17954452]
 [0.17024612]
 [0.65020936]]
mu is  [[0.00948886]]
k= 6
[[0.07583789]
 [0.06809845]
 [0.85606367]]
mu is  [[0.00382177]]
k= 7
[[0.03085966]
 [0.02723938]
 [0.94190096]]
mu is  [[0.00153353]]
k= 8
[[0.01234386]
 [0.01099322]
 [0.97666292]]
mu is  [[0.00061637]]
k= 9
[[0.00493755]
 [0.00447847]
 [0.99058399]]
mu is  [[0.00024772]]
k= 10
[[0.00197502]
 [0.00182552]
 [0.99619946]]
mu is  [[9.94986014e-05]]
k= 11
[[7.90007319e-04]
 [7.42308850e-04]
 [9.98467684e-01]]
mu is  [[3.99340292e-05]]
k= 12
[[3.16002928e-04]
 [3.00935584e-04]
 [9.99383061e-01]]
mu is  [[1.60167866e-05]]
k= 13
[[1.26401171e-04]
 [1.2

In [6]:
#x0 =(1/2, 1/2, 1/2)
A=[[1,1,1]]
b=[[1]]
c=[[1],[1],[0]]
A=np.array(A)
b=np.array(b)
c=np.array(c)

x0 = [[1/2],[1/2],[1/2]]

IPM(A,b,c,x0)

mu is  [[0.78162663]]
k= 0
[[0.46460177]
 [0.23198483]
 [0.3034134 ]]
mu is  [[0.32617538]]
k= 1
[[0.4454689 ]
 [0.23890756]
 [0.31562354]]
mu is  [[0.1433317]]
k= 2
[[0.4195933 ]
 [0.24000383]
 [0.34040287]]
mu is  [[0.06866996]]
k= 3
[[0.37578883]
 [0.22816841]
 [0.39604277]]
mu is  [[0.03547493]]
k= 4
[[0.29294208]
 [0.18884906]
 [0.51820886]]
mu is  [[0.01686052]]
k= 5
[[0.16104639]
 [0.11178653]
 [0.72716708]]
mu is  [[0.00686429]]
k= 6
[[0.06441856]
 [0.0483171 ]
 [0.88726434]]
mu is  [[0.0027842]]
k= 7
[[0.02576742]
 [0.02048133]
 [0.95375125]]
mu is  [[0.00112647]]
k= 8
[[0.01030697]
 [0.00857615]
 [0.98111688]]
mu is  [[0.00045483]]
k= 9
[[0.00412279]
 [0.00355776]
 [0.99231945]]
mu is  [[0.00018333]]
k= 10
[[0.00164912]
 [0.00146512]
 [0.99688576]]
mu is  [[7.37932234e-05]]
k= 11
[[6.59646014e-04]
 [5.99853734e-04]
 [9.98740500e-01]]
mu is  [[2.96679041e-05]]
k= 12
[[2.63858406e-04]
 [2.44459936e-04]
 [9.99491682e-01]]
mu is  [[1.19163091e-05]]
k= 13
[[1.05543362e-04]
 [9.925