In [2]:
import numpy as np

In [3]:
def functionValue(x):
    f=[]
    f.append([np.sin(4*np.pi*x[0,0]*x[1,0])-x[0,0]-2*x[1,0]])
    f.append([(4*np.pi-1)/(4*np.pi)*(np.exp(2*x[0,0])-np.exp(1)) + 4*np.exp(1)*x[1,0]**2- 2 *np.exp(1)*x[0,0]])
    f = np.array(f)
    return f

In [4]:
def functionJacobian(x):
    Df = []
    Df.append([-4 * np.pi * x[1,0] * np.cos(4 * np.pi * x[0,0] * x[1,0]) - 1,-4 * np.pi * x[0,0]* np.cos(4 * np.pi * x[0,0] * x[1,0]) - 2])
    Df.append([((4*np.pi - 1) * np.exp(2 * x[0,0])/2 * np.pi) - 2 * np.exp(1) , 8 * np.exp(1) * x[1,0]])
    Df = np.array(Df)
    return Df

In [6]:
#y = -np.linalg.inv(functionJacobian(x)).dot(functionValue(x))
#x = x + y

x=[[0],[0]]
x = np.array(x)
print("Initial x1,x2")
print(x)
print()

for i in range(2):
    print("k=%d" % i)

    Dx = -np.linalg.inv(functionJacobian(x)).dot(functionValue(x))
    x = x + Dx
    print(x)


Initial x1,x2
[[0]
 [0]]

k=0
[[ 0.12421961]
 [-0.06210981]]
k=1
[[ 0.23115913]
 [-0.09606543]]
