In [17]:
import numpy as np

In [18]:
def functionValue(x):
    f=[]
    f.append([3*x[0,0]-np.cos(x[1,0]*x[2,0])-0.5])
    f.append([x[0,0]**2 - 625 * x[1,0]**2 - 0.25])
    f.append([np.exp(-x[0,0]*x[1,0])+ 20 * x[2,0] + ((10*np.pi-3)/3)])
    f = np.array(f)
    return f

In [19]:
def functionJacobian(x):
    Df = []
    Df.append([3                              , x[2,0]*np.sin(x[1,0]*x[2,0])  , x[1,0]*np.sin(x[1,0]*x[2,0]) ])
    Df.append([2*x[0,0]                       , -1250*x[1,0]                  , 0                            ])
    Df.append([-x[1,0]*np.exp(-x[0,0]*x[1,0]) ,-x[0,0]*np.exp(-x[0,0]*x[1,0]) , 20                           ])
    Df = np.array(Df)
    return Df

In [20]:
def JacobianValue(x):
    value = 3*-1250*x[1,0]*20 + x[1,0]*np.sin(x[1,0]*x[2,0])*2*x[0,0]*-x[0,0]*np.exp(-x[0,0]*x[1,0]) - x[1,0]*np.sin(x[1,0]*x[2,0])*-1250*x[1,0]*-x[1,0]*np.exp(-x[0,0]*x[1,0])-20*x[2,0]*np.sin(x[1,0]*x[2,0])*2*x[0,0]
    return value

In [21]:
x=[[1],[1],[1]]
x = np.array(x)
k = 1

print("Initial x1,x2")
print(x)
print()

while JacobianValue(x) != 0 and k <= 100:
    Dx = -np.linalg.inv(functionJacobian(x)).dot(functionValue(x))
    x = x + Dx
    print("Time: ",end = ' ')
    print(k)
    print(x)
    print()
    print(JacobianValue(x))
    print()
    k = k+1

Initial x1,x2
[[1]
 [1]
 [1]]

Time:  1
[[ 0.90842473]
 [ 0.50045348]
 [-0.50286583]]

-37513.66874546532

Time:  2
[[ 0.49928336]
 [ 0.249958  ]
 [-0.51905224]]

-18745.94783860741

Time:  3
[[ 0.49998069]
 [ 0.12497894]
 [-0.5204787 ]]

-9373.944165542389

Time:  4
[[ 0.49999553]
 [ 0.06248944]
 [-0.5220375 ]]

-4687.037938816278

Time:  5
[[ 0.49999945]
 [ 0.03124471]
 [-0.52281778]]

-2343.523429465123

Time:  6
[[ 0.49999993]
 [ 0.01562235]
 [-0.52320823]]

-1171.7620459987702

Time:  7
[[ 0.49999999]
 [ 0.00781118]
 [-0.5234035 ]]

-585.8810557987542

Time:  8
[[ 0.5       ]
 [ 0.00390559]
 [-0.52350114]]

-292.9405329442627

Time:  9
[[ 0.5       ]
 [ 0.00195279]
 [-0.52354996]]

-146.47026753572675

Time:  10
[[ 0.5       ]
 [ 0.0009764 ]
 [-0.52357437]]

-73.23513402145484

Time:  11
[[ 5.00000000e-01]
 [ 4.88198539e-04]
 [-5.23586571e-01]]

-36.61756707336734

Time:  12
[[ 5.00000000e-01]
 [ 2.44099269e-04]
 [-5.23592673e-01]]

-18.30878355229559

Time:  13
[[ 5.00000000e-01]

In [22]:
print("The solution are")
print(x)
print()
print("The Jacobian value is")
print(JacobianValue(x))

The solution are
[[ 5.00000000e-01]
 [ 3.24023531e-12]
 [-5.23598776e-01]]

The Jacobian value is
-2.4303541460068916e-07
